name: Lint Models
on:
 # оброка лише події типу pull request
 # для декількох значень використовується дужки, наприклад, [push, pull_request]
 pull_request:
  # обробка подій лише для main-гілки
  branches: main
jobs:
 my_linter_test:
  # використання Docker-image із вказаною версією ОС
  runs-on: ubuntu-latest
  steps:
  - name: checkout
    # клонування репозиторія для подальшої роботи з файлами на сервері 
    # в каталозі $GITHUB_WORKSPACE
    uses: "actions/checkout@v3"
  - name: Start linter
    # виконнання декількох послідовних команд shell-інтерпретатором
    run: |
      pip install sqlfluff
      sqlfluff lint $GITHUB_WORKSPACE/sql_query --dialect oracle
