name: Lint Models

on: [push]

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: Install SQLFluff
        run: "pip install sqlfluff"
      - name: Lint models
        run: "sqlfluff lint models"
