# This is a basic workflow to help you get started with Actions

name: PullRequestControl

# Controls when the workflow will run
on: [push]
jobs:
      my_testing:
         runs-on: ubuntu-latest
         steps:
           - name: Print Hello Massage
             run: echo "Hello World!"
