# This is a basic workflow to help you get started with Actions

name: PullRequestControl

# Controls when the workflow will run
on: [push]
jobs:
      my_testing1:
         runs-on: ubuntu-latest
         steps:
           - name: checkout
             uses: "actions/checkout@v3"
           - name: Print Hello Massage
             run: echo "Hello World1!"
           - name: Print python
             run: python --version
           - name: Print pip
             run: pip --version
           - name: Install sqlfluff
             run: pip install sqlfluff
           - name: sqlfluff
             run: sqlfluff version
      my_testing2:
         runs-on: ubuntu-latest
         needs: [my_testing1]
         steps:
           - name: Print Hello Massage
             run: echo "Hello World2!"

