# This is a basic workflow to help you get started with Actions

name: PullRequestControl

# Controls when the workflow will run
on: [push]
jobs:
      my_testing1:
         # використовувати Docker-image із вказаною версією ОС
         runs-on: ubuntu-latest
         steps:
           - name: checkout
             # клонування репозиторія для подальшої роботи з файлами на сервері 
             # в каталозі $GITHUB_WORKSPACE"
             uses: "actions/checkout@v3"
           - name: Print
             run: |
              echo "Workspace:      $GITHUB_WORKSPACE"
              cat $GITHUB_WORKSPACE/README.md
           #- name: Install sqlfluff
           #  run: pip install sqlfluff
           - name: sqlfluff
             run: sqlfluff version
      my_testing2:
         runs-on: ubuntu-latest
         needs: [my_testing1]
         steps:
           - name: Print Hello Massage
             run: echo "Hello World2!"

