# This is a basic workflow to help you get started with Actions 

name: PullRequestControl

# Controls when the workflow will run
on:
 push:
       # обробляти лише main-гілку
       branches: empty # main
jobs:
      my_checkout:
         # використовувати Docker-image із вказаною версією ОС
         runs-on: ubuntu-latest
         steps:
           - name: checkout
             # клонування репозиторія для подальшої роботи з файлами на сервері 
             # в каталозі $GITHUB_WORKSPACE
             uses: "actions/checkout@v3"
           - name: Print Workspace name and README.md
             run: |
              echo "Workspace:      $GITHUB_WORKSPACE"
              cat $GITHUB_WORKSPACE/README.md
      my_linter_test:
         runs-on: ubuntu-latest
         needs: [my_checkout]
         steps:
          - name: checkout
            # клонування репозиторія для подальшої роботи з файлами на сервері 
            # в каталозі $GITHUB_WORKSPACE
            uses: "actions/checkout@v3"
          - name: Start linter
            run: |
             pip install sqlfluff
             sqlfluff lint $GITHUB_WORKSPACE/sql_query --dialect ansi
           
